apiVersion: v1
kind: Service
metadata:
  name: second-app-service
spec:
  selector:
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment # service, job, deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: second-app
      tier: backend
    # matchExpressions:
    #   - {key: app, operator: In, values: [first-app, second-app]}
  template: # details about the Pods
    metadata:
      labels:
        app: second-app
    spec:
      containers:
        - name: second-app
          image: praveen21b/kube-fisrt-app